ISO_TO_WIKIDATA: dict[str, str] = {
    "AF": "Q889",
    "AL": "Q222",
    "DZ": "Q262",
    "AR": "Q414",
    "AM": "Q399",
    "AU": "Q408",
    "AT": "Q40",
    "AZ": "Q227",
    "BD": "Q902",
    "BY": "Q184",
    "BE": "Q31",
    "BR": "Q155",
    "BG": "Q219",
    "CA": "Q16",
    "CL": "Q298",
    "CN": "Q148",
    "CO": "Q739",
    "HR": "Q224",
    "CU": "Q241",
    "CZ": "Q213",
    "DK": "Q35",
    "EG": "Q79",
    "ET": "Q115",
    "FI": "Q33",
    "FR": "Q142",
    "DE": "Q183",
    "GR": "Q41",
    "HU": "Q28",
    "IN": "Q668",
    "ID": "Q252",
    "IR": "Q794",
    "IQ": "Q796",
    "IE": "Q27",
    "IL": "Q801",
    "IT": "Q38",
    "JP": "Q17",
    "KZ": "Q232",
    "KE": "Q114",
    "KP": "Q423",
    "KR": "Q884",
    "MX": "Q96",
    "MA": "Q1028",
    "NL": "Q55",
    "NZ": "Q664",
    "NG": "Q1033",
    "NO": "Q20",
    "PK": "Q843",
    "PE": "Q419",
    "PH": "Q928",
    "PL": "Q36",
    "PT": "Q45",
    "RO": "Q218",
    "RU": "Q159",
    "SA": "Q851",
    "RS": "Q403",
    "ZA": "Q258",
    "ES": "Q29",
    "SE": "Q34",
    "CH": "Q39",
    "TH": "Q869",
    "TR": "Q43",
    "UA": "Q212",
    "AE": "Q878",
    "GB": "Q145",
    "US": "Q30",
    "VN": "Q881",
}

ISO_TO_NAME: dict[str, str] = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BD": "Bangladesh",
    "BY": "Belarus",
    "BE": "Belgium",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "HR": "Croatia",
    "CU": "Cuba",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EG": "Egypt",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "HU": "Hungary",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KP": "North Korea",
    "KR": "South Korea",
    "MX": "Mexico",
    "MA": "Morocco",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NG": "Nigeria",
    "NO": "Norway",
    "PK": "Pakistan",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "RS": "Serbia",
    "ZA": "South Africa",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TH": "Thailand",
    "TR": "Turkey",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "VN": "Vietnam",
}
