"""Seed countries and historical events into the database."""
import logging

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models import Country, HistoricalEvent
from app.utils.country_mapping import ISO_TO_WIKIDATA, ISO_TO_NAME

logger = logging.getLogger("histarix")

# Key historical events per country (iso_a2 -> list of (year, title, description))
HISTORICAL_EVENTS = {
    "KR": [
        (-2333, "고조선 건국", "단군왕검이 고조선을 건국했다고 전해진다."),
        (-57, "신라 건국", "박혁거세가 신라를 건국하였다."),
        (-37, "고구려 건국", "주몽이 고구려를 건국하였다."),
        (-18, "백제 건국", "온조왕이 백제를 건국하였다."),
        (676, "신라의 삼국통일", "신라가 당나라의 세력을 몰아내고 삼국을 통일하였다."),
        (918, "고려 건국", "왕건이 고려를 건국하였다."),
        (1392, "조선 건국", "이성계가 조선을 건국하였다."),
        (1446, "훈민정음 반포", "세종대왕이 훈민정음을 반포하였다."),
        (1592, "임진왜란", "일본이 조선을 침략한 임진왜란이 발발하였다."),
        (1636, "병자호란", "청나라가 조선을 침략한 병자호란이 발생하였다."),
        (1876, "강화도 조약", "일본과 강화도 조약을 체결하며 개항하였다."),
        (1910, "한일병합", "대한제국이 일본에 의해 강제 병합되었다."),
        (1919, "3·1 운동", "독립을 요구하는 3·1 만세 운동이 전국적으로 일어났다."),
        (1945, "광복", "일본의 항복으로 한국이 해방되었다."),
        (1950, "한국전쟁 발발", "북한의 남침으로 한국전쟁이 시작되었다."),
        (1988, "서울 올림픽", "제24회 하계 올림픽이 서울에서 개최되었다."),
        (2002, "한일 월드컵", "FIFA 월드컵이 한국과 일본에서 공동 개최되었다."),
    ],
    "US": [
        (1492, "Columbus reaches Americas", "Christopher Columbus arrived in the Americas."),
        (1607, "Jamestown founded", "The first permanent English settlement was established."),
        (1776, "Declaration of Independence", "The United States declared independence from Britain."),
        (1787, "Constitution adopted", "The U.S. Constitution was ratified."),
        (1861, "Civil War begins", "The American Civil War began between North and South."),
        (1865, "Civil War ends", "The Civil War ended with Union victory; slavery abolished."),
        (1869, "Transcontinental Railroad", "The first transcontinental railroad was completed."),
        (1903, "Wright Brothers flight", "The Wright Brothers achieved the first powered flight."),
        (1929, "Great Depression", "The stock market crashed, beginning the Great Depression."),
        (1941, "Pearl Harbor", "Japan attacked Pearl Harbor; U.S. entered World War II."),
        (1945, "End of WWII", "World War II ended after atomic bombs on Japan."),
        (1963, "JFK assassination", "President John F. Kennedy was assassinated."),
        (1969, "Moon landing", "Apollo 11 landed on the Moon; Neil Armstrong walked on it."),
        (1989, "Fall of Berlin Wall", "The Berlin Wall fell, signaling the end of the Cold War."),
        (2001, "September 11 attacks", "Terrorist attacks destroyed the World Trade Center."),
    ],
    "GB": [
        (1066, "Norman Conquest", "William the Conqueror won the Battle of Hastings."),
        (1215, "Magna Carta", "King John signed the Magna Carta at Runnymede."),
        (1348, "Black Death", "The plague devastated England, killing a third of the population."),
        (1588, "Spanish Armada defeated", "England defeated the Spanish Armada."),
        (1642, "English Civil War", "Civil war began between Parliamentarians and Royalists."),
        (1707, "Act of Union", "England and Scotland united to form Great Britain."),
        (1776, "American colonies lost", "Britain lost the American colonies."),
        (1815, "Battle of Waterloo", "Napoleon was defeated at Waterloo."),
        (1837, "Victorian Era begins", "Queen Victoria began her reign."),
        (1914, "World War I begins", "Britain entered the First World War."),
        (1939, "World War II begins", "Britain declared war on Germany."),
        (1945, "WWII ends", "World War II ended in Allied victory."),
        (1947, "Indian independence", "India gained independence from Britain."),
        (1997, "Hong Kong handover", "Britain returned Hong Kong to China."),
    ],
    "FR": [
        (481, "Frankish Kingdom", "Clovis I united the Franks and founded the Merovingian dynasty."),
        (800, "Charlemagne crowned", "Charlemagne was crowned Emperor of the Romans."),
        (1337, "Hundred Years War begins", "The Hundred Years' War with England began."),
        (1431, "Joan of Arc executed", "Joan of Arc was burned at the stake."),
        (1643, "Louis XIV begins reign", "The Sun King began his 72-year reign."),
        (1789, "French Revolution", "The French Revolution began with the storming of the Bastille."),
        (1799, "Napoleon takes power", "Napoleon Bonaparte seized power in a coup."),
        (1804, "Napoleon becomes Emperor", "Napoleon crowned himself Emperor of France."),
        (1815, "Napoleon defeated", "Napoleon was defeated at Waterloo and exiled."),
        (1870, "Franco-Prussian War", "France was defeated by Prussia."),
        (1914, "World War I", "France fought in the devastating First World War."),
        (1940, "Fall of France", "Germany occupied France in World War II."),
        (1944, "D-Day Liberation", "Allied forces liberated France on D-Day."),
        (1958, "Fifth Republic", "Charles de Gaulle established the Fifth Republic."),
    ],
    "DE": [
        (800, "Charlemagne's Empire", "Charlemagne united much of Western Europe."),
        (962, "Holy Roman Empire", "Otto I was crowned Emperor, founding the Holy Roman Empire."),
        (1517, "Protestant Reformation", "Martin Luther posted his 95 Theses."),
        (1618, "Thirty Years War", "The devastating Thirty Years' War began."),
        (1871, "German unification", "Germany was unified under Prussian leadership."),
        (1914, "World War I", "Germany fought in the First World War."),
        (1918, "Weimar Republic", "The German Empire fell; the Weimar Republic was established."),
        (1933, "Hitler rises to power", "Adolf Hitler became Chancellor of Germany."),
        (1939, "World War II begins", "Germany invaded Poland, starting WWII."),
        (1945, "Germany surrenders", "Germany surrendered, ending WWII in Europe."),
        (1961, "Berlin Wall built", "The Berlin Wall was constructed, dividing East and West."),
        (1989, "Berlin Wall falls", "The Berlin Wall fell, leading to reunification."),
        (1990, "German Reunification", "East and West Germany were officially reunified."),
    ],
    "JP": [
        (710, "Nara Period", "The capital was established at Nara."),
        (794, "Heian Period", "The capital moved to Kyoto; classical Japanese culture flourished."),
        (1185, "Kamakura Shogunate", "The first military government was established."),
        (1467, "Onin War", "Civil war began the Sengoku (Warring States) period."),
        (1600, "Battle of Sekigahara", "Tokugawa Ieyasu won, leading to the Tokugawa Shogunate."),
        (1603, "Edo Period begins", "The Tokugawa Shogunate established peace for 250 years."),
        (1853, "Perry's Black Ships", "U.S. Commodore Perry forced Japan to open its ports."),
        (1868, "Meiji Restoration", "Imperial rule was restored; rapid modernization began."),
        (1905, "Russo-Japanese War", "Japan defeated Russia, emerging as a world power."),
        (1941, "Pearl Harbor attack", "Japan attacked Pearl Harbor, entering WWII."),
        (1945, "Atomic bombs & surrender", "Hiroshima and Nagasaki were bombed; Japan surrendered."),
        (1964, "Tokyo Olympics", "Japan hosted the Summer Olympics, showcasing recovery."),
        (1989, "Heisei Era begins", "Emperor Akihito began the Heisei era."),
    ],
    "CN": [
        (-221, "Qin unifies China", "Qin Shi Huang unified China and became the first Emperor."),
        (-206, "Han Dynasty", "The Han Dynasty was established, lasting over 400 years."),
        (618, "Tang Dynasty", "The Tang Dynasty began, a golden age of Chinese civilization."),
        (960, "Song Dynasty", "The Song Dynasty was established, advancing technology and culture."),
        (1271, "Yuan Dynasty", "Kublai Khan established the Mongol-led Yuan Dynasty."),
        (1368, "Ming Dynasty", "The Ming Dynasty was founded, building the Forbidden City."),
        (1644, "Qing Dynasty", "The Manchu Qing Dynasty conquered China."),
        (1839, "Opium War", "The First Opium War with Britain began."),
        (1911, "Xinhai Revolution", "The revolution overthrew the Qing Dynasty."),
        (1912, "Republic of China", "The Republic of China was established."),
        (1949, "People's Republic", "Mao Zedong proclaimed the People's Republic of China."),
        (1966, "Cultural Revolution", "The Cultural Revolution caused massive upheaval."),
        (1978, "Reform and Opening", "Deng Xiaoping began economic reforms."),
        (2001, "WTO membership", "China joined the World Trade Organization."),
    ],
    "EG": [
        (-3100, "Ancient Egypt unified", "Upper and Lower Egypt were unified under the first pharaoh."),
        (-2560, "Great Pyramid built", "The Great Pyramid of Giza was constructed."),
        (-1332, "Tutankhamun's reign", "The boy pharaoh Tutankhamun ruled Egypt."),
        (-332, "Alexander conquers Egypt", "Alexander the Great conquered Egypt."),
        (-30, "Roman Egypt", "Egypt became a province of the Roman Empire."),
        (641, "Arab conquest", "Arab forces conquered Egypt, introducing Islam."),
        (1250, "Mamluk Sultanate", "The Mamluks seized power in Egypt."),
        (1798, "Napoleon in Egypt", "Napoleon invaded Egypt."),
        (1869, "Suez Canal opens", "The Suez Canal was completed and opened."),
        (1922, "Independence", "Egypt gained independence from Britain."),
        (1952, "Egyptian Revolution", "The monarchy was overthrown in a military revolution."),
        (1956, "Suez Crisis", "Egypt nationalized the Suez Canal."),
        (1979, "Peace with Israel", "Egypt signed the Camp David Accords with Israel."),
    ],
    "IT": [
        (-753, "Rome founded", "According to legend, Rome was founded by Romulus."),
        (-509, "Roman Republic", "The Roman Republic was established."),
        (-27, "Roman Empire", "Augustus became the first Roman Emperor."),
        (476, "Fall of Rome", "The Western Roman Empire fell."),
        (1096, "First Crusade", "Italian city-states played key roles in the Crusades."),
        (1300, "Renaissance begins", "The Italian Renaissance began in Florence."),
        (1861, "Italian Unification", "Italy was unified as a single kingdom."),
        (1915, "Enters WWI", "Italy entered World War I on the Allied side."),
        (1922, "Mussolini rises", "Benito Mussolini and the Fascists took power."),
        (1943, "Fall of Fascism", "Mussolini was deposed; Italy switched sides in WWII."),
        (1946, "Republic established", "Italy became a republic after a referendum."),
    ],
    "RU": [
        (882, "Kievan Rus", "The Kievan Rus state was established."),
        (1240, "Mongol invasion", "The Mongols conquered most of Russia."),
        (1480, "End of Mongol rule", "Russia freed itself from Mongol domination."),
        (1547, "Ivan the Terrible", "Ivan IV became the first Tsar of Russia."),
        (1613, "Romanov Dynasty", "The Romanov dynasty began ruling Russia."),
        (1703, "St. Petersburg founded", "Peter the Great founded St. Petersburg."),
        (1812, "Napoleon invades", "Napoleon invaded Russia and was defeated."),
        (1861, "Serfdom abolished", "Tsar Alexander II abolished serfdom."),
        (1905, "Revolution of 1905", "A wave of political unrest swept Russia."),
        (1917, "Russian Revolution", "The Bolsheviks overthrew the Tsar; Soviet Union began."),
        (1941, "Nazi invasion", "Germany invaded the Soviet Union in Operation Barbarossa."),
        (1945, "Victory in WWII", "The Soviet Union helped defeat Nazi Germany."),
        (1957, "Sputnik launched", "The first artificial satellite was launched into space."),
        (1991, "Soviet Union dissolves", "The Soviet Union collapsed; Russia became independent."),
    ],
    "GR": [
        (-776, "First Olympics", "The first recorded Olympic Games were held at Olympia."),
        (-508, "Athenian Democracy", "Cleisthenes established democracy in Athens."),
        (-480, "Battle of Thermopylae", "300 Spartans made their famous last stand."),
        (-334, "Alexander's conquests", "Alexander the Great began his conquest of the known world."),
        (-146, "Roman conquest", "Greece became part of the Roman Empire."),
        (330, "Byzantine Empire", "Constantine moved the capital to Constantinople."),
        (1453, "Fall of Constantinople", "The Ottoman Turks captured Constantinople."),
        (1821, "Greek War of Independence", "Greece fought for independence from the Ottoman Empire."),
        (1896, "Modern Olympics", "The first modern Olympic Games were held in Athens."),
        (1940, "WWII resistance", "Greece resisted the Italian and German invasions."),
    ],
    "IN": [
        (-2500, "Indus Valley Civilization", "One of the world's earliest civilizations flourished."),
        (-1500, "Vedic Period", "The Vedas were composed; Hindu civilization developed."),
        (-322, "Maurya Empire", "Chandragupta Maurya founded the Maurya Empire."),
        (-265, "Ashoka's reign", "Emperor Ashoka promoted Buddhism across India."),
        (320, "Gupta Empire", "The Gupta Empire began India's Golden Age."),
        (1526, "Mughal Empire", "Babur founded the Mughal Empire."),
        (1600, "East India Company", "The British East India Company began trading in India."),
        (1857, "Indian Rebellion", "The first major rebellion against British rule."),
        (1920, "Gandhi's movement", "Mahatma Gandhi led the non-cooperation movement."),
        (1947, "Independence", "India gained independence from Britain; partition occurred."),
        (1950, "Republic of India", "India adopted its constitution and became a republic."),
    ],
    "BR": [
        (1500, "Portuguese arrival", "Pedro Alvares Cabral claimed Brazil for Portugal."),
        (1822, "Independence", "Brazil declared independence from Portugal."),
        (1888, "Slavery abolished", "Brazil was the last country in the Americas to abolish slavery."),
        (1889, "Republic proclaimed", "The monarchy was overthrown; Brazil became a republic."),
        (1960, "Brasilia built", "The new capital Brasilia was inaugurated."),
        (2014, "FIFA World Cup", "Brazil hosted the FIFA World Cup."),
        (2016, "Rio Olympics", "Rio de Janeiro hosted the Summer Olympics."),
    ],
    "TR": [
        (330, "Constantinople founded", "Constantine the Great founded Constantinople."),
        (1071, "Battle of Manzikert", "Seljuk Turks defeated the Byzantine Empire."),
        (1299, "Ottoman Empire founded", "Osman I founded the Ottoman Empire."),
        (1453, "Constantinople conquered", "Mehmed II conquered Constantinople."),
        (1683, "Siege of Vienna", "The Ottomans were defeated at Vienna."),
        (1923, "Republic of Turkey", "Mustafa Kemal Ataturk founded the Republic of Turkey."),
    ],
    "ES": [
        (711, "Moorish conquest", "Muslim forces conquered most of the Iberian Peninsula."),
        (1492, "Reconquista completed", "Granada fell; Columbus sailed to the Americas."),
        (1588, "Spanish Armada", "Spain's Armada was defeated by England."),
        (1808, "Peninsular War", "Napoleon invaded Spain."),
        (1898, "Spanish-American War", "Spain lost Cuba, Philippines, and Puerto Rico."),
        (1936, "Spanish Civil War", "Civil war between Republicans and Nationalists began."),
        (1975, "Democracy restored", "Franco died; Spain transitioned to democracy."),
    ],
    "MX": [
        (-1500, "Olmec civilization", "The first major Mesoamerican civilization arose."),
        (1325, "Tenochtitlan founded", "The Aztecs founded their capital Tenochtitlan."),
        (1521, "Spanish conquest", "Hernan Cortes conquered the Aztec Empire."),
        (1810, "War of Independence", "Mexico's independence movement began."),
        (1846, "Mexican-American War", "War with the United States resulted in territorial loss."),
        (1910, "Mexican Revolution", "The Mexican Revolution began."),
    ],
    "AU": [
        (1770, "Cook claims Australia", "Captain James Cook claimed Australia for Britain."),
        (1788, "First Fleet arrives", "The First Fleet established a penal colony at Sydney."),
        (1851, "Gold Rush", "Gold was discovered, triggering mass immigration."),
        (1901, "Federation", "The six colonies federated to form the Commonwealth."),
        (1942, "Battle of Coral Sea", "Australia helped defeat Japan in the Coral Sea."),
        (2000, "Sydney Olympics", "Sydney hosted the Summer Olympics."),
    ],
    # --- New countries below ---
    "AF": [
        (-330, "Alexander conquers region", "Alexander the Great conquered the area of modern Afghanistan."),
        (652, "Arab conquest", "Arab armies brought Islam to Afghanistan."),
        (1219, "Mongol invasion", "Genghis Khan invaded and devastated the region."),
        (1747, "Durrani Empire", "Ahmad Shah Durrani founded the modern Afghan state."),
        (1839, "First Anglo-Afghan War", "Britain invaded Afghanistan in the first of three Anglo-Afghan wars."),
        (1919, "Independence from Britain", "Afghanistan gained full independence after the Third Anglo-Afghan War."),
        (1979, "Soviet invasion", "The Soviet Union invaded Afghanistan."),
        (2001, "US-led intervention", "US-led forces invaded after the September 11 attacks."),
    ],
    "AL": [
        (-168, "Roman conquest", "Rome conquered Illyria, including modern Albania."),
        (1190, "Principality of Arberia", "The first Albanian state, the Principality of Arberia, was established."),
        (1444, "Skanderbeg's resistance", "Skanderbeg led Albanian resistance against the Ottoman Empire."),
        (1478, "Ottoman conquest", "Albania fell under Ottoman rule after Skanderbeg's death."),
        (1912, "Independence declared", "Albania declared independence from the Ottoman Empire."),
        (1944, "Liberation from Nazis", "Albania was liberated from Nazi occupation."),
        (1991, "End of communism", "Communist rule ended; democratic transition began."),
    ],
    "DZ": [
        (-1000, "Berber kingdoms", "Berber kingdoms flourished in North Africa."),
        (46, "Roman province", "Algeria became part of the Roman Empire as Mauretania."),
        (709, "Arab conquest", "Arab armies conquered the region, spreading Islam."),
        (1518, "Ottoman rule", "Algeria came under Ottoman Empire control."),
        (1830, "French colonization", "France invaded and colonized Algeria."),
        (1954, "War of Independence begins", "The Algerian War of Independence against France began."),
        (1962, "Independence", "Algeria gained independence from France after a brutal war."),
    ],
    "AR": [
        (1516, "Spanish exploration", "Spanish explorers first reached the Rio de la Plata."),
        (1580, "Buenos Aires founded", "Buenos Aires was permanently established by the Spanish."),
        (1816, "Independence declared", "Argentina declared independence from Spain."),
        (1853, "Constitution adopted", "Argentina adopted its national constitution."),
        (1946, "Peron era begins", "Juan Peron was elected president, transforming Argentine politics."),
        (1976, "Military dictatorship", "A military junta seized power, beginning the Dirty War."),
        (1982, "Falklands War", "Argentina fought Britain over the Falkland Islands."),
        (1983, "Return to democracy", "Democratic rule was restored after the dictatorship."),
    ],
    "AM": [
        (-782, "Kingdom of Urartu", "The fortress of Erebuni (Yerevan) was founded by Urartu."),
        (-190, "Kingdom of Armenia", "The Kingdom of Armenia was established as a major power."),
        (301, "Christianity adopted", "Armenia became the first nation to adopt Christianity as state religion."),
        (1375, "Fall of Armenian Kingdom", "The last Armenian kingdom in Cilicia fell."),
        (1915, "Armenian Genocide", "The Ottoman Empire carried out the genocide of Armenians."),
        (1918, "First Republic", "The First Republic of Armenia was established."),
        (1991, "Independence", "Armenia declared independence from the Soviet Union."),
    ],
    "AT": [
        (976, "Margraviate of Austria", "The Margraviate of Austria was established under the Babenbergs."),
        (1278, "Habsburg rule begins", "The Habsburgs gained control of Austria."),
        (1529, "Siege of Vienna", "The Ottoman Empire besieged Vienna but failed to capture it."),
        (1683, "Second Siege of Vienna", "The Ottomans were defeated again at Vienna."),
        (1804, "Austrian Empire", "The Austrian Empire was formally proclaimed."),
        (1867, "Austro-Hungarian Empire", "The Dual Monarchy of Austria-Hungary was established."),
        (1914, "WWI begins", "The assassination of Archduke Franz Ferdinand triggered World War I."),
        (1918, "Republic proclaimed", "Austria became a republic after the collapse of the empire."),
        (1938, "Anschluss", "Nazi Germany annexed Austria."),
        (1955, "State Treaty", "Austria regained full sovereignty and declared neutrality."),
    ],
    "AZ": [
        (-549, "Achaemenid rule", "The region came under Persian Achaemenid control."),
        (642, "Arab conquest", "Arab armies conquered the region, introducing Islam."),
        (1501, "Safavid Empire", "The Safavid dynasty, originating from Azerbaijan, unified Persia."),
        (1813, "Russian conquest", "Russia gained control of northern Azerbaijan via the Treaty of Gulistan."),
        (1918, "Democratic Republic", "The Azerbaijan Democratic Republic was established, the first secular democracy in the Muslim world."),
        (1920, "Soviet takeover", "The Soviet Union took control of Azerbaijan."),
        (1991, "Independence", "Azerbaijan declared independence from the Soviet Union."),
    ],
    "BD": [
        (1204, "Muslim rule begins", "The Delhi Sultanate conquered Bengal."),
        (1576, "Mughal conquest", "The Mughal Empire conquered Bengal."),
        (1757, "Battle of Plassey", "The British East India Company gained control of Bengal."),
        (1905, "Partition of Bengal", "The British partitioned Bengal, sparking nationalist movements."),
        (1947, "East Pakistan created", "The partition of India created East Pakistan (later Bangladesh)."),
        (1952, "Language Movement", "Protests for Bengali language rights led to the Language Movement."),
        (1971, "Liberation War", "Bangladesh gained independence from Pakistan after a liberation war."),
    ],
    "BY": [
        (980, "Principality of Polotsk", "The Principality of Polotsk emerged as a major Slavic state."),
        (1569, "Polish-Lithuanian rule", "Belarus became part of the Polish-Lithuanian Commonwealth."),
        (1795, "Russian Empire", "Belarus was absorbed into the Russian Empire."),
        (1918, "Brief independence", "The Belarusian People's Republic was briefly declared."),
        (1941, "Nazi occupation", "Nazi Germany occupied Belarus; massive destruction and loss of life."),
        (1986, "Chernobyl disaster", "The Chernobyl nuclear disaster heavily affected Belarus."),
        (1991, "Independence", "Belarus declared independence from the Soviet Union."),
    ],
    "BE": [
        (57, "Roman conquest", "Julius Caesar conquered the Belgae tribes."),
        (843, "Treaty of Verdun", "The Carolingian Empire was divided; Belgium's region split."),
        (1302, "Battle of the Golden Spurs", "Flemish militia defeated French knights at Kortrijk."),
        (1581, "Spanish Netherlands", "The southern Low Countries remained under Spanish control."),
        (1815, "United Kingdom of the Netherlands", "Belgium was merged with the Netherlands after Napoleon's defeat."),
        (1830, "Belgian Revolution", "Belgium declared independence from the Netherlands."),
        (1914, "German invasion in WWI", "Germany invaded neutral Belgium, triggering British entry into WWI."),
        (1940, "German occupation in WWII", "Belgium was occupied by Nazi Germany."),
        (1957, "EEC founding member", "Belgium became a founding member of the European Economic Community."),
    ],
    "BG": [
        (681, "First Bulgarian Empire", "The First Bulgarian Empire was established."),
        (864, "Christianity adopted", "Bulgaria adopted Christianity under Boris I."),
        (1018, "Byzantine conquest", "The Byzantine Empire conquered Bulgaria."),
        (1185, "Second Bulgarian Empire", "The Second Bulgarian Empire was established."),
        (1396, "Ottoman conquest", "Bulgaria fell under Ottoman rule for nearly 500 years."),
        (1878, "Liberation", "Bulgaria was liberated from Ottoman rule after the Russo-Turkish War."),
        (1944, "Soviet influence", "Bulgaria came under Soviet influence after WWII."),
        (1989, "End of communism", "Communist rule ended in Bulgaria."),
    ],
    "CA": [
        (1534, "Jacques Cartier explores", "Jacques Cartier explored the St. Lawrence River and claimed the land for France."),
        (1608, "Quebec City founded", "Samuel de Champlain founded Quebec City."),
        (1759, "Battle of the Plains of Abraham", "British forces defeated the French, gaining control of New France."),
        (1867, "Confederation", "Canada became a self-governing dominion through the British North America Act."),
        (1885, "Transcontinental Railway", "The Canadian Pacific Railway was completed, linking east to west."),
        (1914, "Canada enters WWI", "Canada entered World War I alongside Britain."),
        (1931, "Statute of Westminster", "Canada gained legislative independence from Britain."),
        (1982, "Constitution patriated", "Canada patriated its constitution with the Charter of Rights and Freedoms."),
    ],
    "CL": [
        (1541, "Santiago founded", "Pedro de Valdivia founded Santiago, the capital of Chile."),
        (1818, "Independence", "Chile declared independence from Spain under Bernardo O'Higgins."),
        (1879, "War of the Pacific", "Chile fought Bolivia and Peru in the War of the Pacific."),
        (1891, "Civil War", "A civil war between congress and the president erupted."),
        (1970, "Allende elected", "Salvador Allende became the first Marxist elected president in the Americas."),
        (1973, "Military coup", "General Pinochet overthrew Allende in a US-backed military coup."),
        (1990, "Return to democracy", "Chile returned to democratic rule after Pinochet's dictatorship."),
    ],
    "CO": [
        (1499, "Spanish arrival", "Spanish explorers first arrived on the Colombian coast."),
        (1538, "Bogota founded", "Gonzalo Jimenez de Quesada founded Bogota."),
        (1810, "Independence movement begins", "Colombia's independence movement began."),
        (1819, "Battle of Boyaca", "Simon Bolivar won the decisive Battle of Boyaca, securing independence."),
        (1903, "Panama separates", "Panama separated from Colombia with US backing."),
        (1948, "La Violencia begins", "The assassination of Jorge Eliecer Gaitan sparked a decade of civil conflict."),
        (2016, "Peace agreement", "The Colombian government signed a peace deal with FARC rebels."),
    ],
    "HR": [
        (641, "Croat settlement", "Croats settled in the region during the migration period."),
        (925, "Kingdom of Croatia", "Tomislav became the first King of Croatia."),
        (1102, "Union with Hungary", "Croatia entered a personal union with Hungary."),
        (1527, "Habsburg rule", "Croatia came under Habsburg rule."),
        (1918, "Kingdom of Yugoslavia", "Croatia became part of the Kingdom of Serbs, Croats and Slovenes."),
        (1941, "WWII puppet state", "The Nazis established the puppet Independent State of Croatia."),
        (1991, "Independence", "Croatia declared independence from Yugoslavia."),
        (1995, "End of war", "The Croatian War of Independence ended with Operation Storm."),
    ],
    "CU": [
        (1492, "Columbus arrives", "Christopher Columbus landed in Cuba."),
        (1511, "Spanish colonization", "Spain began colonizing Cuba."),
        (1868, "Ten Years War", "Cuba's first war of independence against Spain began."),
        (1898, "Spanish-American War", "The US defeated Spain; Cuba gained nominal independence."),
        (1953, "Moncada attack", "Fidel Castro attacked the Moncada Barracks, beginning the revolution."),
        (1959, "Cuban Revolution", "Fidel Castro's revolutionaries overthrew the Batista regime."),
        (1962, "Cuban Missile Crisis", "A nuclear standoff between the US and Soviet Union over missiles in Cuba."),
    ],
    "CZ": [
        (863, "Great Moravia", "Saints Cyril and Methodius brought Christianity to Great Moravia."),
        (1212, "Kingdom of Bohemia", "The Golden Bull confirmed Bohemia as a kingdom within the Holy Roman Empire."),
        (1415, "Jan Hus martyred", "Jan Hus was burned at the stake, sparking the Hussite movement."),
        (1618, "Defenestration of Prague", "The event triggered the Thirty Years' War."),
        (1918, "Czechoslovakia founded", "Czechoslovakia was established as an independent state."),
        (1938, "Munich Agreement", "Britain and France allowed Nazi Germany to annex the Sudetenland."),
        (1968, "Prague Spring", "A period of political liberalization was crushed by Soviet invasion."),
        (1989, "Velvet Revolution", "Peaceful protests ended communist rule."),
        (1993, "Czech Republic established", "Czechoslovakia peacefully dissolved into two nations."),
    ],
    "DK": [
        (793, "Viking Age begins", "The Viking Age began with raids across Europe."),
        (965, "Christianity adopted", "King Harald Bluetooth unified Denmark and adopted Christianity."),
        (1397, "Kalmar Union", "Denmark, Sweden, and Norway were united under one crown."),
        (1536, "Reformation", "Denmark adopted Lutheranism as the state religion."),
        (1814, "Loss of Norway", "Denmark ceded Norway to Sweden after the Napoleonic Wars."),
        (1849, "Constitutional monarchy", "Denmark adopted a constitutional monarchy."),
        (1940, "German occupation", "Nazi Germany occupied Denmark during World War II."),
        (1973, "Joins the EEC", "Denmark joined the European Economic Community."),
    ],
    "ET": [
        (-980, "Kingdom of Aksum", "The Kingdom of Aksum rose as a major trading empire."),
        (330, "Christianity adopted", "King Ezana of Aksum adopted Christianity."),
        (1137, "Zagwe Dynasty", "The Zagwe Dynasty came to power; the rock-hewn churches of Lalibela were built."),
        (1270, "Solomonic Dynasty", "The Solomonic Dynasty was restored, claiming descent from King Solomon."),
        (1896, "Battle of Adwa", "Ethiopia defeated Italy at the Battle of Adwa, preserving independence."),
        (1936, "Italian occupation", "Italy occupied Ethiopia until liberation in 1941."),
        (1974, "Derg revolution", "Emperor Haile Selassie was overthrown by the Derg military junta."),
        (1991, "EPRDF takes power", "The Ethiopian People's Revolutionary Democratic Front overthrew the Derg."),
    ],
    "FI": [
        (1155, "Swedish Crusade", "Finland came under Swedish influence through the Northern Crusades."),
        (1581, "Grand Duchy under Sweden", "Finland became a Grand Duchy within the Swedish realm."),
        (1809, "Russian rule", "Finland became an autonomous Grand Duchy of the Russian Empire."),
        (1917, "Independence", "Finland declared independence from Russia."),
        (1939, "Winter War", "Finland fought the Soviet Union in the Winter War."),
        (1944, "Continuation War ends", "Finland signed an armistice with the Soviet Union."),
        (1995, "Joins the EU", "Finland joined the European Union."),
    ],
    "HU": [
        (896, "Magyar conquest", "Magyar tribes conquered the Carpathian Basin."),
        (1000, "Kingdom established", "Stephen I was crowned the first King of Hungary."),
        (1241, "Mongol invasion", "The Mongols devastated Hungary."),
        (1526, "Battle of Mohacs", "The Ottoman Empire defeated Hungary at Mohacs."),
        (1541, "Ottoman occupation", "The Ottomans occupied central Hungary for 150 years."),
        (1867, "Austro-Hungarian Compromise", "Hungary gained co-equal status in the Austro-Hungarian Empire."),
        (1918, "Independence", "Hungary became an independent republic after WWI."),
        (1956, "Hungarian Revolution", "A popular uprising against Soviet rule was crushed."),
        (1989, "End of communism", "Hungary transitioned to democracy."),
    ],
    "ID": [
        (700, "Srivijaya Empire", "The Srivijaya maritime empire dominated Southeast Asian trade."),
        (1293, "Majapahit Empire", "The Majapahit Empire arose as a major Hindu-Buddhist state."),
        (1511, "Portuguese arrive", "Europeans first arrived in the Indonesian archipelago."),
        (1602, "Dutch East India Company", "The Dutch established colonial control through the VOC."),
        (1942, "Japanese occupation", "Japan occupied the Dutch East Indies during WWII."),
        (1945, "Independence declared", "Sukarno and Hatta proclaimed Indonesian independence."),
        (1965, "Anti-communist purge", "A military-led purge killed hundreds of thousands."),
        (1998, "Reformasi", "The fall of Suharto led to democratic reforms."),
    ],
    "IR": [
        (-550, "Achaemenid Empire", "Cyrus the Great founded the Persian Achaemenid Empire."),
        (-330, "Alexander's conquest", "Alexander the Great conquered the Persian Empire."),
        (224, "Sasanian Empire", "The Sasanian Empire restored Persian greatness."),
        (651, "Arab conquest", "Arab armies conquered Persia, bringing Islam."),
        (1501, "Safavid Empire", "The Safavid dynasty established Shia Islam as the state religion."),
        (1906, "Constitutional Revolution", "Iran's Constitutional Revolution established a parliament."),
        (1953, "CIA coup", "A CIA-backed coup overthrew Prime Minister Mossadegh."),
        (1979, "Islamic Revolution", "The Iranian Revolution overthrew the Shah and established an Islamic republic."),
    ],
    "IQ": [
        (-3500, "Sumerian civilization", "The Sumerians developed one of the world's first civilizations in Mesopotamia."),
        (-1792, "Babylonian Empire", "Hammurabi united Mesopotamia and created his famous law code."),
        (-612, "Fall of Assyria", "The Neo-Assyrian Empire fell to a coalition of Babylonians and Medes."),
        (636, "Arab conquest", "Arab Muslim forces conquered Mesopotamia at the Battle of Qadisiyyah."),
        (762, "Baghdad founded", "The Abbasid Caliphate founded Baghdad as its capital."),
        (1258, "Mongol sack of Baghdad", "The Mongols destroyed Baghdad, ending the Abbasid Caliphate."),
        (1920, "British Mandate", "Iraq came under British Mandate after World War I."),
        (1932, "Independence", "Iraq gained formal independence from Britain."),
        (2003, "US-led invasion", "A US-led coalition invaded Iraq and toppled Saddam Hussein."),
    ],
    "IE": [
        (432, "Saint Patrick arrives", "Saint Patrick brought Christianity to Ireland."),
        (795, "Viking raids begin", "Vikings began raiding and settling in Ireland."),
        (1169, "Norman invasion", "Anglo-Norman forces invaded Ireland."),
        (1541, "Kingdom of Ireland", "Henry VIII declared himself King of Ireland."),
        (1845, "Great Famine", "The Great Famine killed over a million people and caused mass emigration."),
        (1916, "Easter Rising", "Republicans staged an armed insurrection against British rule."),
        (1922, "Irish Free State", "The Irish Free State was established after the War of Independence."),
        (1973, "Joins the EEC", "Ireland joined the European Economic Community."),
    ],
    "IL": [
        (-1000, "Kingdom of Israel", "King David established Jerusalem as the capital of Israel."),
        (-586, "Babylonian Exile", "The Babylonians destroyed the Temple and exiled the Jews."),
        (-63, "Roman rule", "Pompey conquered Judea for Rome."),
        (70, "Destruction of Second Temple", "The Romans destroyed the Second Temple in Jerusalem."),
        (1917, "Balfour Declaration", "Britain declared support for a Jewish homeland in Palestine."),
        (1948, "State of Israel established", "Israel declared independence; the first Arab-Israeli war began."),
        (1967, "Six-Day War", "Israel captured the West Bank, Gaza, Sinai, and Golan Heights."),
        (1993, "Oslo Accords", "Israel and the PLO signed the Oslo Peace Accords."),
    ],
    "KZ": [
        (552, "Turkic Khaganate", "The Turkic Khaganate controlled the Central Asian steppes."),
        (1218, "Mongol conquest", "Genghis Khan conquered the region."),
        (1465, "Kazakh Khanate", "The Kazakh Khanate was established."),
        (1731, "Russian protectorate", "The Kazakh hordes began accepting Russian protection."),
        (1936, "Kazakh SSR", "Kazakhstan became a full Soviet Socialist Republic."),
        (1991, "Independence", "Kazakhstan declared independence from the Soviet Union."),
    ],
    "KE": [
        (100, "Bantu migration", "Bantu-speaking peoples migrated into the region."),
        (900, "Swahili city-states", "Swahili trading cities flourished along the coast."),
        (1498, "Portuguese arrive", "Vasco da Gama reached the Kenyan coast."),
        (1895, "British East Africa", "Britain established the East Africa Protectorate."),
        (1952, "Mau Mau Uprising", "The Mau Mau rebellion against British colonial rule began."),
        (1963, "Independence", "Kenya gained independence from Britain under Jomo Kenyatta."),
        (2010, "New constitution", "Kenya adopted a new constitution with significant reforms."),
    ],
    "KP": [
        (-2333, "Gojoseon", "According to legend, Dangun founded Gojoseon."),
        (-37, "Goguryeo", "The kingdom of Goguryeo was founded in the north."),
        (668, "Unified Silla", "Silla unified the Korean peninsula."),
        (918, "Goryeo dynasty", "The Goryeo dynasty was established."),
        (1392, "Joseon dynasty", "The Joseon dynasty began."),
        (1945, "Division of Korea", "Korea was divided into North and South at the 38th parallel."),
        (1948, "DPRK established", "The Democratic People's Republic of Korea was established under Kim Il-sung."),
        (1950, "Korean War", "North Korea invaded South Korea, starting the Korean War."),
    ],
    "MA": [
        (-25, "Roman Mauretania", "The region became a client kingdom of Rome."),
        (682, "Arab conquest", "Arab forces brought Islam to Morocco."),
        (789, "Idrisid dynasty", "The first Moroccan Muslim dynasty was founded."),
        (1062, "Almoravid Empire", "The Almoravid dynasty founded Marrakesh and built a vast empire."),
        (1912, "French protectorate", "Morocco became a French and Spanish protectorate."),
        (1956, "Independence", "Morocco gained independence from France."),
    ],
    "NL": [
        (57, "Roman frontier", "The Rhine formed the northern frontier of the Roman Empire."),
        (1568, "Dutch Revolt begins", "The Eighty Years' War against Spain began."),
        (1602, "Dutch East India Company", "The VOC was founded, launching the Dutch Golden Age."),
        (1648, "Independence recognized", "The Treaty of Westphalia recognized Dutch independence."),
        (1795, "French occupation", "France occupied the Netherlands during the Napoleonic era."),
        (1815, "Kingdom established", "The Kingdom of the Netherlands was established."),
        (1940, "German occupation", "Nazi Germany occupied the Netherlands."),
        (1945, "Liberation", "The Netherlands was liberated by Allied forces."),
        (1957, "EEC founding member", "The Netherlands co-founded the European Economic Community."),
    ],
    "NZ": [
        (1300, "Polynesian settlement", "Polynesians settled New Zealand and became the Maori people."),
        (1642, "European discovery", "Dutch explorer Abel Tasman was the first European to sight New Zealand."),
        (1840, "Treaty of Waitangi", "The Treaty of Waitangi was signed between the British and Maori chiefs."),
        (1893, "Women's suffrage", "New Zealand became the first country to grant women the right to vote."),
        (1907, "Dominion status", "New Zealand became a dominion within the British Empire."),
        (1947, "Full independence", "New Zealand adopted the Statute of Westminster, gaining full independence."),
    ],
    "NG": [
        (1000, "Nok civilization", "The Nok civilization produced remarkable terracotta sculptures."),
        (1100, "Ife Kingdom", "The Kingdom of Ife flourished as a major Yoruba city-state."),
        (1440, "Benin Empire", "The Benin Empire became a powerful West African state."),
        (1804, "Sokoto Caliphate", "Usman dan Fodio established the Sokoto Caliphate through jihad."),
        (1861, "British colonization begins", "Britain annexed Lagos, beginning colonial control."),
        (1960, "Independence", "Nigeria gained independence from Britain."),
        (1967, "Biafran War", "The Nigerian Civil War began over Biafran secession."),
    ],
    "NO": [
        (793, "Viking Age begins", "Vikings from Norway began raiding across Europe."),
        (872, "Unification", "Harald Fairhair unified Norway into a single kingdom."),
        (1030, "Christianity established", "King Olaf II established Christianity in Norway."),
        (1397, "Kalmar Union", "Norway joined the Kalmar Union with Denmark and Sweden."),
        (1814, "Constitution adopted", "Norway adopted its constitution at Eidsvoll."),
        (1905, "Independence from Sweden", "Norway peacefully dissolved its union with Sweden."),
        (1940, "German occupation", "Nazi Germany occupied Norway during World War II."),
        (1969, "Oil discovery", "Oil was discovered in the North Sea, transforming Norway's economy."),
    ],
    "PK": [
        (-2500, "Indus Valley Civilization", "The Indus Valley Civilization flourished in the region."),
        (712, "Arab conquest", "Muhammad bin Qasim conquered Sindh, introducing Islam."),
        (1206, "Delhi Sultanate", "Muslim sultanates ruled the region for centuries."),
        (1526, "Mughal Empire", "The Mughal Empire was established, ruling the subcontinent."),
        (1857, "British rule solidified", "After the Indian Rebellion, Britain took direct control."),
        (1940, "Lahore Resolution", "The Muslim League demanded a separate Muslim state."),
        (1947, "Independence", "Pakistan was created as a separate Muslim state during partition."),
        (1971, "Bangladesh separates", "East Pakistan became independent Bangladesh after civil war."),
    ],
    "PE": [
        (-3000, "Caral civilization", "The Norte Chico civilization, one of the oldest in the Americas, arose."),
        (1200, "Inca Empire begins", "The Inca civilization began expanding from Cusco."),
        (1438, "Inca expansion", "Pachacuti expanded the Inca Empire across western South America."),
        (1532, "Spanish conquest", "Francisco Pizarro conquered the Inca Empire."),
        (1821, "Independence declared", "Jose de San Martin declared Peruvian independence."),
        (1879, "War of the Pacific", "Peru fought against Chile in the War of the Pacific."),
        (1980, "Shining Path insurgency", "The Maoist guerrilla group Shining Path began its insurgency."),
    ],
    "PH": [
        (900, "Laguna Copperplate", "The earliest known written document in the Philippines was inscribed."),
        (1521, "Magellan arrives", "Ferdinand Magellan reached the Philippines."),
        (1565, "Spanish colonization", "Spain established permanent colonial control."),
        (1896, "Philippine Revolution", "The revolution against Spanish rule began."),
        (1898, "Independence declared", "The Philippines declared independence from Spain."),
        (1942, "Japanese occupation", "Japan occupied the Philippines during World War II."),
        (1946, "Full independence", "The Philippines gained full independence from the United States."),
        (1986, "People Power Revolution", "A peaceful revolution toppled the Marcos dictatorship."),
    ],
    "PL": [
        (966, "Baptism of Poland", "Duke Mieszko I adopted Christianity, founding the Polish state."),
        (1025, "Kingdom of Poland", "Boleslaw I was crowned the first King of Poland."),
        (1386, "Polish-Lithuanian Union", "Poland and Lithuania united, creating a vast European power."),
        (1569, "Polish-Lithuanian Commonwealth", "The Commonwealth was formally established."),
        (1795, "Third Partition", "Poland was partitioned and disappeared from the map for 123 years."),
        (1918, "Independence restored", "Poland regained independence after World War I."),
        (1939, "WWII invasion", "Germany and the Soviet Union invaded Poland, starting WWII."),
        (1945, "Communist rule", "Poland came under Soviet-imposed communist rule."),
        (1989, "Solidarity triumph", "The Solidarity movement led to free elections and the end of communism."),
    ],
    "PT": [
        (1139, "Kingdom of Portugal", "Afonso Henriques declared himself King of Portugal."),
        (1249, "Reconquista completed", "Portugal expelled the Moors from the Algarve."),
        (1415, "Age of Exploration begins", "Portugal captured Ceuta, beginning its maritime expansion."),
        (1498, "Vasco da Gama reaches India", "Vasco da Gama reached India by sea."),
        (1500, "Brazil discovered", "Pedro Alvares Cabral reached Brazil."),
        (1755, "Lisbon earthquake", "A devastating earthquake destroyed much of Lisbon."),
        (1910, "Republic proclaimed", "The Portuguese monarchy was overthrown."),
        (1974, "Carnation Revolution", "A peaceful military coup ended decades of dictatorship."),
    ],
    "RO": [
        (106, "Roman Dacia", "Emperor Trajan conquered Dacia, making it a Roman province."),
        (271, "Roman withdrawal", "Rome withdrew from Dacia."),
        (1330, "Wallachia established", "Wallachia became an independent principality."),
        (1600, "Brief unification", "Michael the Brave briefly unified Wallachia, Moldavia, and Transylvania."),
        (1859, "Principalities united", "Wallachia and Moldavia united to form Romania."),
        (1918, "Greater Romania", "Transylvania united with Romania after World War I."),
        (1947, "Communist takeover", "Romania became a communist People's Republic."),
        (1989, "Revolution", "A violent revolution overthrew the communist Ceausescu regime."),
    ],
    "SA": [
        (570, "Birth of Prophet Muhammad", "The Prophet Muhammad was born in Mecca."),
        (622, "Hijra", "Muhammad migrated from Mecca to Medina, founding the Muslim community."),
        (632, "Islamic expansion", "After Muhammad's death, Arab armies rapidly expanded the caliphate."),
        (1744, "First Saudi State", "Muhammad ibn Saud allied with Muhammad ibn Abd al-Wahhab."),
        (1902, "Riyadh captured", "Abdulaziz ibn Saud captured Riyadh, beginning Saudi unification."),
        (1932, "Kingdom of Saudi Arabia", "The Kingdom of Saudi Arabia was officially founded."),
        (1938, "Oil discovered", "Oil was discovered in Saudi Arabia, transforming the nation."),
    ],
    "RS": [
        (1166, "Nemanjic dynasty", "Stefan Nemanja founded the medieval Serbian state."),
        (1217, "Kingdom of Serbia", "Serbia became a kingdom."),
        (1389, "Battle of Kosovo", "Serbia was defeated by the Ottoman Empire at the Battle of Kosovo."),
        (1459, "Ottoman conquest", "Serbia fell fully under Ottoman control."),
        (1804, "Serbian Revolution", "The First Serbian Uprising began against Ottoman rule."),
        (1878, "Independence recognized", "Serbia's independence was internationally recognized."),
        (1918, "Kingdom of Yugoslavia", "Serbia became part of the Kingdom of Serbs, Croats and Slovenes."),
        (2006, "Modern independence", "Serbia became an independent state after Montenegro's separation."),
    ],
    "ZA": [
        (300, "Bantu migration", "Bantu-speaking peoples migrated into southern Africa."),
        (1652, "Dutch settlement", "Jan van Riebeeck established a Dutch settlement at the Cape."),
        (1795, "British takeover", "Britain took control of the Cape Colony."),
        (1835, "Great Trek", "Boer settlers migrated inland in the Great Trek."),
        (1899, "Boer War", "The Second Boer War between Britain and the Boer republics began."),
        (1910, "Union of South Africa", "The Union of South Africa was formed."),
        (1948, "Apartheid begins", "The National Party implemented apartheid policies."),
        (1990, "Mandela released", "Nelson Mandela was released after 27 years in prison."),
        (1994, "End of apartheid", "South Africa held its first democratic elections; Mandela became president."),
    ],
    "SE": [
        (793, "Viking Age", "Swedish Vikings (Varangians) traded and raided across Eastern Europe."),
        (1000, "Christianity adopted", "Sweden gradually adopted Christianity."),
        (1397, "Kalmar Union", "Sweden joined the Kalmar Union with Denmark and Norway."),
        (1523, "Independence from Denmark", "Gustav Vasa liberated Sweden and became king."),
        (1630, "Thirty Years War intervention", "Sweden intervened as a major Protestant power in the war."),
        (1718, "End of Great Power era", "The death of Charles XII ended Sweden's era as a great power."),
        (1809, "Loss of Finland", "Sweden lost Finland to Russia."),
        (1995, "Joins the EU", "Sweden joined the European Union."),
    ],
    "CH": [
        (1291, "Swiss Confederation founded", "Three cantons swore the Federal Charter, founding Switzerland."),
        (1499, "De facto independence", "Switzerland achieved practical independence from the Holy Roman Empire."),
        (1515, "Permanent neutrality", "After the Battle of Marignano, Switzerland adopted neutrality."),
        (1648, "Independence recognized", "The Peace of Westphalia recognized Swiss independence."),
        (1798, "French invasion", "Napoleon's forces invaded and created the Helvetic Republic."),
        (1815, "Neutrality guaranteed", "The Congress of Vienna guaranteed Swiss perpetual neutrality."),
        (1848, "Federal state", "Switzerland adopted a federal constitution."),
    ],
    "TH": [
        (1238, "Sukhothai Kingdom", "The Sukhothai Kingdom was established as the first major Thai state."),
        (1351, "Ayutthaya Kingdom", "The Ayutthaya Kingdom became a dominant power in Southeast Asia."),
        (1767, "Fall of Ayutthaya", "Burma destroyed Ayutthaya, ending the kingdom."),
        (1782, "Chakri Dynasty", "King Rama I founded the Chakri Dynasty and established Bangkok."),
        (1855, "Bowring Treaty", "Thailand opened to international trade while maintaining independence."),
        (1932, "Constitutional revolution", "A bloodless revolution transformed Thailand into a constitutional monarchy."),
        (1941, "Japanese occupation", "Japan occupied Thailand during World War II."),
    ],
    "UA": [
        (882, "Kievan Rus", "Kyiv became the capital of the Kievan Rus state."),
        (988, "Christianity adopted", "Vladimir the Great adopted Christianity for Kievan Rus."),
        (1240, "Mongol destruction of Kyiv", "The Mongols sacked and destroyed Kyiv."),
        (1648, "Cossack Hetmanate", "Bohdan Khmelnytsky led a Cossack uprising, creating the Hetmanate."),
        (1783, "Russian annexation of Crimea", "The Russian Empire annexed Crimea."),
        (1917, "Ukrainian People's Republic", "Ukraine declared independence during the Russian Revolution."),
        (1932, "Holodomor", "The Soviet-engineered famine killed millions of Ukrainians."),
        (1991, "Independence", "Ukraine declared independence from the Soviet Union."),
    ],
    "AE": [
        (630, "Islam arrives", "Islam spread to the Arabian Peninsula region."),
        (1820, "British treaties", "Local rulers signed treaties with Britain, creating the Trucial States."),
        (1958, "Oil discovered", "Oil was discovered in Abu Dhabi."),
        (1971, "UAE established", "Seven emirates united to form the United Arab Emirates."),
        (1985, "Emirates airline founded", "Emirates airline was established, boosting Dubai's global profile."),
        (2010, "Burj Khalifa opens", "The world's tallest building opened in Dubai."),
    ],
    "VN": [
        (-2879, "Van Lang Kingdom", "According to legend, the first Vietnamese state was founded."),
        (-111, "Chinese domination", "China conquered Vietnam, beginning over a thousand years of rule."),
        (938, "Independence from China", "Ngo Quyen defeated the Chinese at the Battle of Bach Dang River."),
        (1010, "Ly Dynasty", "The Ly Dynasty moved the capital to Hanoi."),
        (1858, "French colonization begins", "France began its conquest of Vietnam."),
        (1945, "Independence declared", "Ho Chi Minh declared Vietnamese independence."),
        (1954, "Battle of Dien Bien Phu", "Vietnam defeated France at Dien Bien Phu, ending French rule."),
        (1975, "Fall of Saigon", "North Vietnam captured Saigon, reunifying Vietnam."),
    ],
}


async def seed_countries(session: AsyncSession) -> None:
    """Seed countries table if empty."""
    result = await session.execute(select(Country).limit(1))
    if result.scalar_one_or_none():
        return

    for iso_code, name in ISO_TO_NAME.items():
        wikidata_id = ISO_TO_WIKIDATA.get(iso_code)
        country = Country(
            iso_a2=iso_code,
            name_en=name,
            wikidata_id=wikidata_id,
        )
        session.add(country)
    await session.commit()


async def seed_historical_events(session: AsyncSession) -> None:
    """Seed historical events table if empty."""
    result = await session.execute(select(HistoricalEvent).limit(1))
    if result.scalar_one_or_none():
        return

    count = 0
    for iso_code, events in HISTORICAL_EVENTS.items():
        if iso_code not in ISO_TO_NAME:
            continue
        for year, title, description in events:
            event = HistoricalEvent(
                title=title,
                description=description,
                year=year,
                date=f"{abs(year):04d}" if year >= 0 else f"-{abs(year):04d}",
                country_iso=iso_code,
                category="general",
                importance=2,
            )
            session.add(event)
            count += 1
    try:
        await session.commit()
        logger.info("Seeded %d historical events", count)
    except Exception as e:
        await session.rollback()
        logger.error("Failed to seed events: %s", e)
